// <auto-generated />
using System;
using DroneLocationTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DroneLocationTracker.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200127003427_AddSpeedToLocations")]
    partial class AddSpeedToLocations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("DroneLocationTracker.Data.Models.Drone", b =>
                {
                    b.Property<Guid>("DroneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("DroneId");

                    b.HasIndex("LastLocationId")
                        .IsUnique();

                    b.ToTable("Drones");

                    b.HasData(
                        new
                        {
                            DroneId = new Guid("f358be15-2e6f-4235-802a-27ca93a5fef7"),
                            Name = "Test Drone 1"
                        },
                        new
                        {
                            DroneId = new Guid("5dee1226-3865-45de-aa97-e0d9f80ab51f"),
                            Name = "Test Drone 2"
                        },
                        new
                        {
                            DroneId = new Guid("4e8873e5-09d5-4eee-8602-e6f6046daaad"),
                            Name = "Test Drone 3"
                        },
                        new
                        {
                            DroneId = new Guid("81372f59-1cd0-4577-9d7d-ad04d1e35e99"),
                            Name = "Test Drone 4"
                        },
                        new
                        {
                            DroneId = new Guid("aa2252b6-7f41-41a1-9d5a-bd8b4064fd39"),
                            Name = "Test Drone 5"
                        });
                });

            modelBuilder.Entity("DroneLocationTracker.Data.Models.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DroneId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Speed")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DroneLocationTracker.Data.Models.Drone", b =>
                {
                    b.HasOne("DroneLocationTracker.Data.Models.Location", "LastLocation")
                        .WithOne("Drone")
                        .HasForeignKey("DroneLocationTracker.Data.Models.Drone", "LastLocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
